flowchart LR
  P["电源管理模块"] --> M["STM32主控模块"]
  S["传感器模块<br/>PIR / DHT / MQ-2 / AS608 / OV7670"] --> M
  M --> A["执行器模块<br/>门锁 / 燃气阀 / 蜂鸣器"]
  M --> N["网络通信模块<br/>ESP8266"]
  M --> D["存储模块<br/>SD卡"]
  N --> C["云端与移动端"]
