gantt
    title 任务调度时序甘特图
    dateFormat  X
    axisFormat %Ss
    section 高优先级
    Task_Security_Alarm : 0, 1
    Task_Security_Alarm : 2, 1
    Task_Security_Alarm : 4, 1
    section 中优先级
    Task_Wifi_MQTT      : 1, 2
    Task_Fingerprint    : 1, 1
    Task_Sensor         : 2, 1
    Task_Capture        : 3, 1
    section 低优先级
    Task_SystemMonitor  : 2, 1
    Task_SystemMonitor  : 5, 1
    Task_SystemMonitor  : 7, 1
